source 'ssh://git@git.mistong.com:10022/ios-framework/mistong-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'EffectiveTool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#pod 'XHXNetwork'
#pod 'XHXLog'
#pod 'CKKit'
  # Pods for EffectiveTool

end
